[project]
name = "booktracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django-bootstrap5>=25.1",
    "django>=5.1.7",
]
