# Generated by Django 5.1.7 on 2025-03-08 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_record_book_alter_record_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
    ]
