# Generated by Django 5.1.7 on 2025-03-18 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shelf',
            options={'verbose_name': 'Полка', 'verbose_name_plural': 'Полки'},
        ),
        migrations.RenameField(
            model_name='shelf',
            old_name='book',
            new_name='books',
        ),
    ]
