# Generated by Django 5.1.7 on 2025-04-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_delete_record'),
        ('shelves', '0003_alter_shelf_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='shelves', to='books.book', verbose_name='Книги'),
        ),
    ]
